name: Run integration tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Anbox Cloud
      uses: canonical/anbox-cloud-github-action@main
      with:
        channel: 1.23/stable
        ubuntu-pro-token: ${{ secrets.UBUNTU_PRO_TOKEN }}
        
    - name: Set up Anbox Cloud token
      run: |
        echo "Setting up Anbox Cloud token"
        export ANBOX_CLOUD_TOKEN=${{ secrets.ANBOX_CLOUD_TOKEN }}

    - name: List current directory
      run: |
        pwd
        ls -l ./images/

    - name: Add Android image
      run: |
        amc image add jammy:android13:amd64 ./images/android13.tar.xz

    - name: Create Android instance
      id: create-instance
      run: |
        set -x
        id="$(amc launch -r -s adb jammy:android13:amd64)"
        amc wait -c status=running "$id"
        echo "id=$id" >> "$GITHUB_OUTPUT"
        
    - name: Access Android over ADB
      run: |
        sudo apt install -y adb
        id=${{ steps.create-instance.outputs.id }}
        addr="$(amc show "$id" --format=json | jq -r .network.address)"
        adb connect "$addr":5559
        
    - name: Run tests
      run: |
        model="$(adb shell getprop ro.product.model)"
        echo "Detected model: $model"
        if [ "$model" != "Anbox" ]; then
          echo "Test failed: Expected model 'Anbox', got '$model'"
          exit 1
        fi
